---
- name: test the script
  hosts: local
  tasks:
    - name: creating ec2 instance
      terraform:
        project_path: '/home/rohitbhakare/talentica/terraform'
        state: present
      register: result
    - name: printing info 
      debug:
        var: result.outputs.instance_public_dns.value 
    - name: added line 
      lineinfile:
        firstmatch: yes
        insertafter: "[aws]"                                                                           #added under new host
        path: /etc/ansible/hosts
        line: "{{ result.outputs.instance_public_dns.value }}"
